[package]
name = "kmitl_wifi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
tokio = { version = "1.20.1", features = ["full"] }
wifi-rs = "0.2.2"
